
server:

  port: 8080



spring:

  datasource:

    username: yzh

    password: 123

    url: jdbc:mysql://106.55.49.252:3306/users?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

    driver-class-name: com.mysql.jdbc.Driver



mybatis:

  mapper-locations: classpath:mapper/*

  type-aliases-package: com.example.entity



#showSql

logging:

  level:

    com:

      example:

        mapper : debug
